config/routes.rb
require 'sidekiq/web'

Iso::Application.routes.draw do
  devise_for :admin_users

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :photographs, only: [:index, :show] do
    collection do
      get :explore
      get :recommended
      get :search
      get :random
      get :favourites
      get :following
      get :seeking_feedback
    end

    member do
      post :recommend
    end

    resources :favourites, only: [:create, :destroy]
  end

  resources :comment_threads do
    resources :comments, only: [:create, :update, :destroy] do
      member do
        get :toggle
      end
    end
  end

  resources :collections, only: [:index, :show] do
    collection do
      get :explore
    end
  end

  resources :categories, shallow: true, only: [:show] do
    resources :photographs, only: [:index]
    resources :collections, only: [:index]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :mark_all_as_read
    end
  end

  resources :users, shallow: true, only: [:show] do
    resources :collections, only: [:index, :show] do
      resources :photographs, only: [:index]
    end

    resources :followings, only: [:create, :destroy]
    resources :photographs, only: [:index]
  end

  devise_for :users, path: :account, controllers: { 
    registrations: "devise_extensions/registrations",
    invitations: "devise_extensions/invitations"
  }
  namespace :account do
    resources :photographs do
      collection do
        get :public
        get :private
        get :unsorted
        post :mass_update
        get :typeahead
      end
    end

    resources :collections, shallow: true do
      resources :photographs do
        collection do
          post :mass_update
        end
      end
    end

    resources :authorisations, only: [:index]

    root to: "account#dashboard"
  end

  get "/p/:id" => "photographs#show", as: :short_photo
  get "/u/:id" => "users#show", as: :short_user
  get "/c/:id" => "collections#show", as: :short_collection
  get "/status" => "pages#up", as: :status
  get "/stats" => "pages#stats", as: :stats
  get "/sitemap" => "pages#sitemap", as: :sitemap
  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms

  get "/auth/:provider/callback" => "account/authorisations#create"

  root to: "pages#home"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment_thread, touch: true
  has_many :notifications, as: :notifiable

  acts_as_tree dependent: :destroy

  validates :user_id, :comment_thread_id, :body, presence: true
  validates :parent_id, inclusion: { in: -> (c) { c.comment_thread.comments.pluck(:id) } }, allow_blank: true

  scope :published, -> { where(published: true) }

  after_create :notify
  def notify
    title = comment_thread.threadable.title.blank? ? I18n.t("untitled") : comment_thread.threadable.title

    unless user == comment_thread.user
      # Notify owner
      notifications.create(
        send_email: true,
        user: comment_thread.user,
        subject: I18n.t("comments.notifications.subject", user: user.name, on: title),
        body: I18n.t("comments.notifications.body", user: user.name, on: title)
      )
    end
    
    # Notify replyee
    if child? && parent.user != comment_thread.user
      notifications.create(
        user: parent.user,
        subject: I18n.t("comments.notifications.reply.subject", user: user.name, on: title),
        body: I18n.t("comments.notifications.reply.body", user: user.name, on: title)
      )
    end
  end

  def can_be_seen_by?(current_user)
    Rails.cache.fetch([self, current_user]) do
      if current_user == user || current_user == comment_thread.user
        true
      elsif child? && ancestors.map(&:user).include?(current_user)
        true
      elsif published?
        true
      else
        false
      end
    end
  end

  def toggle_visibility
    self.published = !published
    saved = save

    if saved && published
      title = comment_thread.threadable.title.blank? ? I18n.t("untitled") : comment_thread.threadable.title

      notifications.create(
        user: user,
        subject: I18n.t("comments.notifications.published.subject", on: title)
      )
    end

    if child? && saved && published
      self.ancestors.find_each do |a|
        a.update_attribute(:published, published)
      end
    end

    saved
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!

  before_filter do
    @comment_thread = CommentThread.find(params[:comment_thread_id])
    authorize! :read, @comment_thread
  end

  def create
    parent_id = comment_params.delete(:parent_id)
    @comment = @comment_thread.comments.new(comment_params)
    @comment.user = current_user

    if parent_id.present?
      @parent = @comment_thread.comments.find(parent_id)
      @parent.children << @comment
    end

    authorize! :create, @comment
    
    if @comment.save
      respond_with @comment do |f|
        f.html { render partial: "comments/comment", layout: false, locals: { comment: @comment } }
      end
    else
      respond_with @comment do |f|
        f.html { render partial: "comments/form", layout: false, locals: { comment: @comment }, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = @comment_thread.comments.find(params[:id])
    authorize! :update, @comment

    if @comment.update_attributes(comment_params)
      respond_with @comment do |f|
        f.html { render partial: "comments/comment", layout: false, locals: { comment: @comment } }
      end
    else
      respond_with @comment do |f|
        f.html { render partial: "comments/form", layout: false, locals: { comment: @comment }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = @comment_thread.comments.find(params[:id])
    authorize! :destroy, @comment

    if @comment.destroy
      respond_with @comment do |f|
        f.html { redirect_to :back }
      end
    else
      respond_with @comment, status: :bad_request do |f|
        f.html { redirect_to :back }
      end
    end
  end

  def toggle
    @comment = @comment_thread.comments.find(params[:id])
    authorize! :moderate, @comment

    if @comment.toggle_visibility
      head :ok
    else
      head :bad_request
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
- if comment.can_be_seen_by?(current_user)
  article[id="comment-#{comment.id}" class="comment #{comment.published? ? 'published' : 'unpublished'}" itemprop="comment" itemscope itemtype="http://schema.org/Comment"]
    div class="main"
      - cache([comment, comment.user, :avatar_and_body]) do
        - if comment.user.avatar.present?
          aside class="avatar"
            = image_tag comment.user.avatar.thumb("50x50#").jpg.url, width: 50, height: 50, alt: ""

        section class="body" itemprop="text"
          = simple_format comment.body

        .clear

      footer
        div class="row"
          div class="large-8 columns left"
            - cache([comment, comment.user, :author_and_status]) do
              span class="author" itemprop="author"
                = link_to comment.user.name, short_user_path(comment.user.username)

              time datetime=(comment.created_at.utc) itemprop="datePublished"
                = l comment.created_at, format: :long

              - status_class = comment.published ? "hidden" : ""
              div class="label secondary radius status #{status_class}"
                - if comment.child?
                  = t("comments.child_unpublished") 
                - else
                  = t("comments.unpublished")

          div class="large-4 columns right"
            div class="actions"
              - if can? :moderate, comment
                - button_class = comment.published ? "published success" : "unpublished secondary"
                = link_to toggle_comment_thread_comment_path(comment.comment_thread, comment), class: "button small radius toggle #{button_class}", "data-remote" => true do
                  span class="published"
                    = t("comments.unpublish")
                  span class="unpublished"
                    = t("comments.publish")

              - if user_signed_in? && current_user == comment.user
                = link_to t("comments.delete"), comment_thread_comment_path(comment.comment_thread, comment), method: :delete, class: "button small alert radius"

              - if user_signed_in?
                = link_to t("comments.reply"), "#", class: "button small radius", "data-toggle-reply" => true

      .clear

    div class="replies comment-thread"
      div[class="reply" data-reply]
        - cache([comment, :form]) do
          = render partial: "comments/form", locals: { comment: comment.comment_thread.comments.new(parent_id: comment.id) }

      div class="comments"
        = render comment.children.order("created_at DESC").includes(:children, :user)

app/views/comments/_form.html.slim
= simple_form_for [comment.comment_thread, comment], html: { "data-remote" => true } do |f|
  fieldset class="row"
    div class="large-9 columns"
      = f.input :body, label: false
      = f.input :parent_id, as: :hidden
    
    div class="large-3 columns"
      = f.button :submit, class: "success expand small", "data-disable-with" => t("comments.saving")