config/routes.rb
require 'sidekiq/web'

Iso::Application.routes.draw do
  devise_for :admin_users

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :photographs, only: [:index, :show] do
    collection do
      get :explore
      get :recommended
      get :search
      get :random
      get :favourites
      get :following
      get :seeking_feedback
    end

    member do
      post :recommend
    end

    resources :favourites, only: [:create, :destroy]
  end

  resources :comment_threads do
    resources :comments, only: [:create, :update, :destroy] do
      member do
        get :toggle
      end
    end
  end

  resources :collections, only: [:index, :show] do
    collection do
      get :explore
    end
  end

  resources :categories, shallow: true, only: [:show] do
    resources :photographs, only: [:index]
    resources :collections, only: [:index]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :mark_all_as_read
    end
  end

  resources :users, shallow: true, only: [:show] do
    resources :collections, only: [:index, :show] do
      resources :photographs, only: [:index]
    end

    resources :followings, only: [:create, :destroy]
    resources :photographs, only: [:index]
  end

  devise_for :users, path: :account, controllers: { 
    registrations: "devise_extensions/registrations",
    invitations: "devise_extensions/invitations"
  }
  namespace :account do
    resources :photographs do
      collection do
        get :public
        get :private
        get :unsorted
        post :mass_update
        get :typeahead
      end
    end

    resources :collections, shallow: true do
      resources :photographs do
        collection do
          post :mass_update
        end
      end
    end

    resources :authorisations, only: [:index]

    root to: "account#dashboard"
  end

  get "/p/:id" => "photographs#show", as: :short_photo
  get "/u/:id" => "users#show", as: :short_user
  get "/c/:id" => "collections#show", as: :short_collection
  get "/status" => "pages#up", as: :status
  get "/stats" => "pages#stats", as: :stats
  get "/sitemap" => "pages#sitemap", as: :sitemap
  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms

  get "/auth/:provider/callback" => "account/authorisations#create"

  root to: "pages#home"
end

app/views/pages/about.html.slim
- cache(:about, expires_in: 10.minutes) do
  section id="pages-about"
    header class="row"
      div class="large-12 columns"
        h1= t("about.title")

    div class="row"
      section class="points small-12 large-8 large-offset-2 columns"
        header
          h2= "Some of the reasons why we think you should join us:"

        article
          h3= "It's free and fair"
          p
            | Free accounts aren't treated like secondary citizens here. Everyone has 
              equal input into how the site works and the direction we take.
              If you have any suggestions, bug reports, or other feedback then we'd
              love to hear it! Send it over to
              <a href="mailto:support@photographer.io">support@photographer.io</a>.

        article
          h3= "We're open source"
          p
            | Our code is open source and available under an MIT license #{link_to 'on GitHub', 'https://github.com/afternoonrobot/photographer-io'}. Help fix bugs, add new features, and
              make this the community you want it to be.

        article
          h3= "No advertising"
          p
            | We hate advertising, which is why you'll <b>never</b> see it on 
              Photographer.io. The site will soon be supported by subscriptions, and we
              may use affiliate links for camera gear etc in future; but we will never run
              adverts.

        article
          h3= "We make money in an obvious way"
          p
            | There's no hocus pocus here. Subscriptions will be coming soon (and at a
              very reasonable price), and these are how the site will be funded. There
              are no investors, no advertisers, and no selling of your data.

        article
          h3= "Likes are dead, long live the Recommendation"
          p
            | We don't use 'Likes' on Photographer.io. Instead every user can make a
              maximum of #{ISO[:defaults][:recommendation_quota]} recommendations per day.
              A recommendation helps promote the photo on our 
              <a href="/photographs/recommended">recommended page</a> but will soon
              recommend the photo to your followers too.

          p
            | Recommendations should be given out for photos which you think are great,
              not necessarily the ones you love the most; that's what Favourites are for!

        article
          h3= "Our commenting system is different"
          p
            | Comments on Photographer.io work more like threads on a traditional 
              message board/forum; you choose a subject for people to comment on. This
              is aimed to help increase the amount of useful feedback you get, rather
              than "OMG LOVE IT". Comments are only visible to the creator and the photo
              owner by default (and the parent comment's owner if it's a reply). This
              means that you get to choose which comments appear on your photos. They
              are <i>your</i> photos after all; shouldn't you choose what appears
              alongside them?

        article
          h3= "Privacy and security are really important to us"
          p
            | We take privacy and security seriously. The entire site and all related
              services (such as image hosting) are served over SSL, passwords are stored
              using <a href="http://bcrypt.sourceforge.net/">bcrypt</a>, and we respond
              to any security issues immediately.
          p
            | Privacy: <a href="#{t('privacy_policy')}">Check out our privacy policy</a>
              or <a href="mailto:privacy@photographer.io">email us with any queries</a>.
            br
            | Security: If you have any security issues or bugs to report, please email
              them to 
              <a href="mailto:security@photographer.io">security@photographer.io</a>.

        article
          h3= "How do we compare to other photo communities?"

          table
            thead
              tr
                th
                th= "Flickr"
                th= "500px"
                th= "Photographer.io"
            tbody
              thead
                tr
                  th colspan="4"
                    = "Free Accounts"
              tr
                th= "Photo uploads"
                td= "1TB"
                td= "20 photos per week"
                td= "100 photos per month *"

              tr
                th= "Albums/Sets/Collections"
                td= "Unlimited"
                td= "Limited"
                td= "Unlimited"

              thead
                tr
                  th colspan="4"
                    = "Everything Else"
              tr
                th= "Advertising"
                td= "Yes"
                td= "No"
                td= "Never"
              tr
                th= "Site-wide SSL"
                td= "Optional"
                td= "No"
                td= "Always"
                
          aside class="notes"
            p
              | * Can be increased by inviting your friends! Details are in your 
                account page.

        article class="sign-up"
          header
            h3= "Interested? Create your free account!"

          div class="button-container"
            = link_to t("about.sign_up"), new_user_registration_path, class: "button success large radius"

app/views/pages/home.html.slim
- content_for(:body_class, "darkroom")

section id="pages-home"
  article id="hero-photograph"
    - photo = @top_photos.sample || Photograph.view_for(current_user).first
    - if photo.present?
      = link_to photograph_path(photo) do
        - if photo.has_precalculated_sizes?
          = photo_tag photo, :homepage
        - else
          - if photo.landscape?
            = photo_tag photo, "2000x", quality: 80
          - else
            = photo_tag photo, "2000x1400#", quality: 80
    
      div id="hero-blurb"
        header
          h2= t("home.title")
          h4= simple_format t("home.blurb", \
            name: link_to(photo.user.name, short_user_path(photo.user.username)), image_path: photograph_path(photo),
            word: t("home.words").sample)

          - unless user_signed_in?
            div class="buttons"
              = link_to t("home.about"), about_path, class: "button small"

              span class="or"
                = t("home.or")

              = link_to t("home.sign_up"), new_user_registration_path, class: "button success small"

app/views/pages/sitemap.xml.slim
- cache(:sitemap, expires_in: 15.minutes) do
  - base_url = "https://www.photographer.io"
  doctype xml

  urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    url
      loc== base_url
      lastmod= w3c_date(Time.now)
      changefreq= "always"

    url
      loc== [base_url, explore_photographs_path].join
      lastmod= w3c_date(@photographs.last.updated_at)
      changefreq= "always"

    url
      loc== [base_url, recommended_photographs_path].join
      lastmod= w3c_date(Time.now)
      changefreq= "always"

    - @photographs.find_each do |photo|
      url
        loc== [base_url, photograph_path(photo)].join
        lastmod= w3c_date(photo.updated_at)
        changefreq= "hourly"
        priority= "1"

    url
      loc== [base_url, explore_collections_path].join
      lastmod= w3c_date(@collections.last.updated_at)
      changefreq= "always"

    - @collections.find_each do |collection|
      url
        loc== [base_url, collection_path(collection)].join
        lastmod= w3c_date(collection.updated_at)
        changefreq= "daily"
        priority= "1"

    - cache([:sitemap, :categories], expires_in: 1.day) do
      - @categories.each do |category|
        url
          loc== [base_url, category_path(category.slug)].join
          lastmod= w3c_date(Time.now)
          changefreq= "daily"
          priority="1"

app/views/pages/terms.html.slim
section id="pages-terms"
  div class="row"
    div class="small-12 large-8 large-offset-2 columns"
      article id="terms"
        == @terms_html